### ISSUE TITLE
Maxwell Home world crashes

### ISSUE THREAD

**Issue by ThemInspectors** [Serpens66/DST-Adventure-Mod#3]
Reaching the final chapter crashes the game.

Relevant part of the log:
https://pastebin.com/Y2zUqa3X

**Comment by Serpens66** [comment]
huh? Are you sure you are playing with my current build, at best the one from steam?
The crash is caused by the maxwell_camera, which is added within the static layout via scenario.
But I already removed it.

**Comment by ThemInspectors** [comment]
Yes I am playing on the latest version. Although, come to think of it, it might be related to the previous issue of the bargain start. It might be the case that instead of running the fixed staticlayouts you're providing it runs the game's outdated copies of them which causes the issue. 
EDIT: I'm working on a PR currently and will submit it soon

**Comment by Serpens66** [comment]
I dont have that much knowledge about github, but I guess you are currently working with the version here on github?
On steam I already made ~3 new updates to the mods, how can we make sure that also your changes can be added?

Should I manually merge your PR with my current version? Should I update the github to my current version before your PR? Or what should I do?

**Comment by ThemInspectors** [comment]
Just pushing your versions to github is fine, as long as we haven't edited the same line it should be alright

**Comment by Serpens66** [comment]
solved with latest update
