### ISSUE TITLE
Boat disable option is not work in GitHub version mod

### ISSUE THREAD

**Issue by Wing-summer** [Serpens66/DST-Adventure-Mod#5]
First, I should make an apology to you for not keeping my credit to make some little changes. I think I can not realize it. Recently, I'm busy on my work and I lost my 2FA authorization on my working PC so I am keeping logging out for a long time.

I found no way to delete receipe filter in a proper way. Also your code to disable boat is not worked. I think it's too late to disable it in `DoTaskInTime` function.

I suggest you can disable the boat with following code that can completely disable it:

```lua
for _,v in ipairs(GLOBAL.CRAFTING_FILTERS.SEAFARING.recipes) do
	GLOBAL.AllRecipes[v].level = GLOBAL.TECH.LOST
end
```

And anothor question, When you update your this mod on steam? :smile:

**Comment by Serpens66** [comment]
Hi, totally forgot about it.
But still no clue what to do about sharkboi. Removing prefabs might work, but no clue how to change the ground.
I do not plan to dig into this more, so if you want to write code to remove the sharkboi stuff and test if it works and is not generated again on each game-load, let me know.

Just tested the boat-thing ingame with the current steam version. It works like it should, the think thank is Tech.Lost and can not be built if you chose "wormholes" in the modsettings and for Maxwell-Door-World use "preconfigured".
The code you suggested does the same like I do (except that yours is forbidding more). I will use your code to deactivate all boat recipes if I do another update fro Adventure mod in the future, but as I said, the current code works fine to disable the think-thank on my side.

"this mod" is up to date on steam. Teleportato is not, but I can push the update now, it will only change the title translation-stuff

**Comment by Wing-summer** [comment]
OK. Thanks for your reply.
